### PR TITLE
Fixed issue with APT dependency checker not respecting provided packages

### LINKED ISSUE #75: makedeb fails to find dependencies when they use `<` or `<=` as a relationship operator
### Issue

When using either `>` or `>=` as a version relationship operator (i.e. `bash>1` or `bash>=6`), makedeb gives the following error when attempting to install build dependencies:

```
[!] The following build dependencies are missing:
  [->] bash (
```

Inspecting the built package's `control` file is writing the dependency correctly though.

### Installation source

APT Repository

### Installed release type

Alpha

### Installed makedeb version

8.6.0-1

### Installed makepkg version

N/A

### LINKED ISSUE #87: makedeb doesn't handle provided packages for dependency resolution correctly
### Issue

Say I have the `go-bin` package on the MPR installed, which provides for the `golang-go` package.

If I add `depends=('golang-go')` to a PKGBUILD, makedeb doesn't currently think the `golang-go` dependency is satisfied, though it is from the `go-bin` package.

### Installation source

APT Repository

### Installed release type

Alpha

### Installed makedeb version

8.6.3-1

### Installed makepkg version

N/A

### PR DESCRIPTION
**Pull request by hwittenborn**
Closes #87.

Also redid some files to use four-spaced indents, as well as added vim modelines.

### CODE REVIEW

File: src/makedeb/functions/dependency_checks/install_missing_dependencies.sh [hunk 1]
```diff
@@ -1,30 +1,33 @@
...
-      
-      for i in "${missing_dependencies_no_relations[@]}" "${missing_build_dependencies_no_relations[@]}"; do
-        msg2 "${i}"
-      done
-      exit 1
+
+    msg2 "Installing required build dependencies..."
+
+    if [[ "${target_os}" == "debian" ]]; then
+        if ! sudo apt-get satisfy "${apt_args[@]}" -- "${missing_dependencies[@]}" "${missing_build_dependencies[@]}"; then
```
Comment (hwittenborn) [inline src/makedeb/functions/dependency_checks/install_missing_dependencies.sh:9]: This is an important change - we were using `apt-get install` previously, but using `apt-get satisfy` gives us more reliability into the versions of packages we install as we can specify relationship operators (i.e. `golang-go (>> 2)` instead of just `golang-go`).

This was reported to not work on Debian Buster (#15), but that's going to be EOL soon, and I think it's worth the trade off if the majority of makedeb users face a benefit by it.

**Review by lpuv — APPROVED** [review]
LGTM
